apiVersion: v1
kind: PersistentVolume
metadata:
  name: crankypv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/Raid1/amcmahon/crankypv
    server: 192.168.0.11
